name: IoT Central Solution Builder Release Workflow

# Manual trigger
on: [workflow_dispatch]
    
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run make
    - name: Publish
      env:
        GITHUB_TOKEN: ${{secrets.SOLUTION_BUILDER_SECRET}}
      run: npm run publish
